server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.0:3306/dbname?characterEncoding=utf8
    username: root
    password: root

string:
  str1: Hello \n Spring Boot.
  str2: 'Hello \n Spring Boot.'
  str3: "Hello \n Spring Boot."

student1:
  id: 1
  name: Java
  age: 18

student2: {id: 2,name: C++,age: 18}

dbtypes1:
  # 集合的名字
  name:
    - mysql
    - sqlserver
    - db2


dbtypes2: {name: [mysql,sqlserver,db2]}