#设置当前运行环境
Spring:
  profiles:
    active: dev
#配置mybatis保存路径
mybatis:
  mapper-locations: classpath:mybatis/**Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 开启 MyBatis SQL 打印
logging:
  level:
    com:
      example:
        demo: debug